INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Zmije levantská','Macrovipera lebetina','plaz','had',FALSE,'Asie',TRUE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Zmije menší','Vipera ursinii','plaz','had',FALSE,'Asie',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Zmije menší - rákošská','Vipera ursinii','plaz','had',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Zmije nosorohá','Bitis nasicornis','plaz','had',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Zmije obecná','Vipera berus','plaz','had',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Papoušek modrohřbetý','Forpus xanthopterygius','pták','',FALSE,'Amerika',TRUE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Papoušek nádherný','Polytelis swainsonii','pták','',FALSE,'Amerika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Papoušek niamský','Poicephalus crassus','pták','',FALSE,'Amerika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Papoušek noční','Geopsittacus occidentalis','pták','',FALSE,'Amerika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Papoušek patagonský','Cyanoliseus patagonus','pták','',FALSE,'Afrika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Papoušek překrásný','Psephotus pulcherrimus','pták','',FALSE,'Afrika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Pes horský','Lycalopex culpaeus','savec','pes',TRUE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Pes hřívnatý','Chrysocyon brachyurus','savec','pes',TRUE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Pes hyenový','Lycaon pictus','savec','pes',TRUE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Pes krátkouchý','Atelocynus microtis','savec','pes',TRUE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Pes pralesní','Speothos venaticus','savec','pes',TRUE,'Evropa',TRUE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Pes ušatý','Otocyon megalotis','savec','pes',,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Holoubek diamantový','Geopelia cuneata','pták','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Husa krátkozobá','Anser brachyrhynchus','pták','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Husa landeská','Anser anser f. domesticus','pták','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Husa lippská','Anser anser f. domesticus','pták','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Husa malá','Anser erythropus','pták','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Samojed','Samoyede','savec','pes',FALSE,'Evropa',TRUE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Saranče horská','Miramella alpina','hmyz','',FALSE,'Afrika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Saranče lesklá','Chrysochraon dispar','hmyz','',FALSE,'Afrika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Siamská kočka','Siamese Cat','savec','kočka',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Sibiřský husky','Siberian Husky','savec','pes',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Datel černý','Dryocopus martius','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Datel hnědý','Celeus elegans','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Sifaka malý','Propithecus verreauxi','','',FALSE,'Amerika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Afghánský chrt','Afghan Hound','savec','pes',FALSE,'Asie',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Bažant Elliotův','Syrmaticus ellioti','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Bažant královský','Syrmaticus reevesii','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Bažant obecný','Phasianus colchicus','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Chameleon obrovský','Furcifer oustaleti','plaz','',FALSE,'Afrika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Chameleon pardálí','Furcifer pardalis','plaz','',FALSE,'Afrika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Emu hnědý','Dromaius novaehollandiae','ptak','',FALSE,'Austrálie',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Foxteriér hladkosrstý','Fox Terrier Smooth','','pes',TRUE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Gekon lemovaný','','plaz','jester',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Gekon madagaskarský','Paroedura pictus','plaz','jester',FALSE,'Austrálie',TRUE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Gekon obrovský','Gekko gecko','plaz','jester',FALSE,'Austrálie',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Gekon saharský','Stenodactylus petrii','plaz','jester',FALSE,'Afrika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Gekon Steudnerův','Chondrodactylus turneri','plaz','jester',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Holub Arabský bublák','','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Holub Bavorský voláč','','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Holub Berlínský dlouhozobý rejdič','','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Holub Berlínský krátkozobý rejdič','','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Holub Berlínský rousný rejdič','','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Kachna kampbelka','','ptak','',FALSE,'Asie',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Kachna orpingtonská','','ptak','',FALSE,'Asie',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Kachna overberžská','','ptak','',FALSE,'Asie',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Kachna pekingská','','ptak','',FALSE,'Asie',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Kachna pižmová','Cairina moschata f. dom.','ptak','',FALSE,'Asie',TRUE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Kachna pomořanská','','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Kachna rouenská','Caneton rouennais','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Racek bouřní','Larus canus','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Racek černohlavý','Ichthyaetus melanocephalus','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Racek chechtavý','Chroicocephalus ridibundus','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Racek malý','Hydrocoloeus minutus','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Racek mořský','Larus marinus','ptak','',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Racek stříbřitý','Larus argentatus','ptak','',FALSE,'Antarktida',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Racek šedý','Larus hyperboreus','ptak','',FALSE,'Amerika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Serval','Leptailurus serval','','',FALSE,'',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Užovka hladká','Coronella austriaca','plaz','had',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Užovka chřestýší','Nerodia taxispilota','plaz','had',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Užovka levhartí','Elaphe situla','plaz','had',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Užovka maurská','Natrix maura','plaz','had',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Užovka obojková','Natrix natrix','plaz','had',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Užovka ostronosá','Gonyosoma oxycephala','plaz','had',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Užovka páskovaná','Nerodia fasciata','plaz','had',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Užovka podplamatá','Natrix tessellata','plaz','had',FALSE,'Evropa',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Varan drsnokrký','Varanus rudicollis','plaz','jester',FALSE,'Austrálie',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Varan Mertensův','Varanus mertensi','plaz','jester',FALSE,'Austrálie',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Varan nilský','Varanus niloticus','plaz','jester',FALSE,'Afrika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Varan ostnoocasý','Varanus acanthurus','plaz','jester',FALSE,'Afrika',FALSE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Varan skvrnitý','Varanus salvator','plaz','jester',FALSE,'Afrika',TRUE);
INSERT INTO zivocich (nazev,latina,rise,podrise,domaci,kontinent,chraneny) values ('Zajíc polární','Lepus arcticus','savec','',FALSE,'Evropa',TRUE);
